### ISSUE TITLE
Publish to Office store

### ISSUE THREAD

**Issue by amay077** [nuitsjp/CopyToMarkdownAddIn#1]
I hope install this from [Office store](https://store.office.com/).
Store provides easy installing and can reach for global users! 👍

**Comment by nuitsjp** [comment]
For "Office Store" and "Office for Mac" must be recreated in a different architecture.
I think trying to do in the following project.
https://github.com/nuitsjp/CopyToMarkdownForStore

**Comment by amay077** [comment]
Thanks!
I'll watch it. 👀

**Comment by nuitsjp** [comment]
Excel Addin for Store is not support Clipboad.
Side loading did not work in Mac Excel. (Windows loads if it loads sideways.)
It is impossible to realize until the Addin API supports clipboard.
For this reason, I will close it once.
