### ISSUE TITLE
インストール出来なくなっています

### ISSUE THREAD

**Issue by NOGPON** [nuitsjp/CopyToMarkdownAddIn#11]
このアドインにはいつもお世話になっています。
新しい環境へインストールしようとしたら、以下のようなエラーによってインストールが失敗します。エラーの文面を読むと証明書に問題が有るようなのですが...

```
このアプリケーションのカスタマイズされた機能は動作しません。Copy to Markdown AddIn の配置マニフェストに署名するときに使用された証明書が信頼されていないか、アプリケーションが信頼された場所にありません。詳細については管理者に問い合わせてください。

-----------------------------------------

名前: Copy to Markdown AddIn
インストール元: file:///C:/Users/[UserName]/Documents/CopyToMarkdownAddIn_2_1_1_0/Copy to Markdown AddIn_2_1_1_0/Copy to Markdown AddIn.vsto

************** 例外テキスト **************
System.Security.SecurityException: このアプリケーションのカスタマイズされた機能は動作しません。Copy to Markdown AddIn の配置マニフェストに署名するときに使用された証明書が信頼されていないか、アプリケーションが信頼された場所にありません。詳細については管理者に問い合わせてください。
   場所 Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   場所 Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   場所 Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   場所 Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   場所 Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
失敗したアセンブリのゾーン:
MyComputer
```

**Comment by nuitsjp** [comment]
確認が遅くなり申し訳ありません。
私の方で動作確認しましたが、問題なくインストールできました。
おそらく、以下の注意事項のzip解答前の「許可する」が実施されていないのではないかと思います。
いったんIssueはクローズしますが、これで解決できない場合、再度ご連絡ください。

<b><span style="color: #ff0000">※要注意※  
zipファイルのダウンロード後、展開する前に必ずファイルのプロパティを開き、「ブロックの解除」をチェックした上で「OK」ボタンを押してください。  
</span></b>
![](https://raw.githubusercontent.com/nuitsjp/CopyToMarkdownAddIn/master/docs/images/zip.png)

**Comment by NOGPON** [comment]
ZIPファイルの「ブロックの解除」チェックはONにしていますが、変わらずインストールに失敗します。
setup.exe の証明書が信頼されていないと出ているので、これが原因だと思うのですが、こちらで回避する方法は有りますでしょうか？

![image](https://user-images.githubusercontent.com/6956554/79632109-2db3ed80-8198-11ea-8b3e-45081378cb3a.png)

**Comment by nuitsjp** [comment]
解消されないということなので、再度オープンします。

**Comment by nuitsjp** [comment]
証明書は正式な機関から発行されたものではないので（年間数万円するので・・・）、そこにはそうでます。ただ、ローカルディスクに置いて「ブロックの解除」をすると、確認の後にインストール自体はできるはずです。

PCのローカルディスクに置いてもダメだとすると、私の方で再現できないので推奨できる方法がすぐにはありません（時間がかかる方法が無いことはないので、数か月の内なら対応したいとは思っていますが、ちょっと約束できません）。

解決策はあるのですが次の問題があります。それを理解した上で問題なければインストールしてみてください。
- 私が今後同じ証明書を利用して作成したアプリケーションが、正式な証明書によって署名されていると表示される（つまり私を信用する）

上記が問題ないのであれば（申し訳ないですが、もしご理解できないのであればお勧めしません）、つぎの方法でインストールしてみてください。

setup.exeのプロパティを開く。
![ss07-0011](https://user-images.githubusercontent.com/16175660/79671056-5a045400-8202-11ea-806e-8b21989f71d6.png)

デジタル署名タブから「詳細」を開く。
![ss07-0012](https://user-images.githubusercontent.com/16175660/79671059-625c8f00-8202-11ea-9d0c-eb1f1f71101e.png)

「証明書の表示」を開く。
![ss07-0013](https://user-images.githubusercontent.com/16175660/79671070-73a59b80-8202-11ea-8967-0894a3910382.png)

「証明書のインストール」を開く。
![ss07-0014](https://user-images.githubusercontent.com/16175660/79671085-8d46e300-8202-11ea-993e-67d7c1d46173.png)

「ローカルコンピューター」を選び「次へ」を選択する。
![ss07-0020](https://user-images.githubusercontent.com/16175660/79671104-b8c9cd80-8202-11ea-85c8-af40e741234c.png)

「証明書をすべてつぎのストアに配置する」を選択し、「参照」を開く。
![ss07-0016](https://user-images.githubusercontent.com/16175660/79671113-ce3ef780-8202-11ea-8734-1512b519cb59.png)

「信頼された発行元」を選択し「OK」を押す。
![ss07-0022](https://user-images.githubusercontent.com/16175660/79671123-e1ea5e00-8202-11ea-9d20-3e6f10475d0f.png)

あとはそのまま最後まで登録してください。
そのあとsetup.exeを実行していただければインストールできるはずだと思います。

**Comment by NOGPON** [comment]
証明書のインポート方法まで詳しく回答いただき、ありがとうございます。
しかし残念ながら、「信頼された発行元」に入れても、インストール時のエラーは変わらず発生します。
また念のため、インポートした証明書を削除した後、「信頼されたルート証明機関」に入れて試したものの、そちらも変わらずでした。

インストール出来ない事象が発生しているのは サブ作業環境で、メイン作業環境では使用できています。本アドインが使えないのは不便ではあるものの 「急いで・今すぐ 対応してほしい」 という程ではありませんので、気が向いたときにでも対応して頂けたら幸いです。
（原因調査のためのログ収集など、出来る範囲で協力は致します。）

**Comment by nuitsjp** [comment]
お試しいただき、ありがとうございます。
またご協力いただけるということで、大変助かります。

ただ、現時点では何をお願いしたらいいのか、私も把握できていません。
ちょっと時期は未定ですが、根本的に配布方法を変更したいと考えておりますので、その際はまたご協力いただけますと幸いです。

**Comment by nuitsjp** [comment]
インストーラーを根本的に変更してみました。
過去のバージョンは削除してから実行してみてください。

https://github.com/nuitsjp/CopyToMarkdownAddIn/releases/tag/Pre-Release-3_0_0_0

プレビューとしていますが、私の環境でインストールできない事象が再現できていないためで、「インストールさえうまくいけば」製品自体は正式版と同様のものです。
NOGPONさんが正常にインストールできて実行できた場合は、このまま正式リリースに格上げします。

良かったらお試しください。
よろしくお願いいたします。

**Comment by NOGPON** [comment]
プレビュー版インストーラにて無事にインストールでき、  
markdown→Excel、Excel→markdown 共に機能することを確認しました。  
素早い対応、ありがとうございます。

**Comment by nuitsjp** [comment]
確認ありがとうございます！
ではこちらはクローズとさせていただき、正式リリースの作業に入らせていただこうと思います。
