### ISSUE TITLE
Broken markdown when a text contains `|`

### ISSUE THREAD

**Issue by tanaka-takayoshi** [nuitsjp/CopyToMarkdownAddIn#12]
When a text contains `|`, a generated markdown is brokes because `|` is the separator of the markdown table.
![2020-08-09_01h27_14](https://user-images.githubusercontent.com/846156/89724215-15aff480-da3b-11ea-927b-0624de47b386.png)
![2020-08-09_01h27_54](https://user-images.githubusercontent.com/846156/89724217-19dc1200-da3b-11ea-8438-945fafb9fe18.png)

I'm wondering we can workaround by replacing (escaping) `|` with `&#124;`.

**Comment by nuitsjp** [comment]
Thank you for your comment. 
I hope to fix this within a week at the earliest.
I'm sorry if I'm late due to a busy work schedule.

**Comment by nuitsjp** [comment]
We have released a new Release 2.1.2.0 to fix this bug.
