### ISSUE TITLE
2行目の実装変更について

### ISSUE THREAD

**Issue by nuitsjp** [nuitsjp/CopyToMarkdownAddIn#2]
現在、以下のルールで実装されているます。

水平方向のアライメントの指定によって、列単位に以下のように設定する
- 未指定 or 左寄せ　|-|  
- 中央寄せ　|:-:|  
- 右寄せ　|-:|  

現時点で以下の問題が寄せられています。  
- Qiitaでは |-| が認知されない。Qiita仕様に合わせるためには左寄せは|:-|が好ましい  
- Redmineでは|:--|のように間に挟まる文字列は３文字以上必要  

ということで現在、以下のように実装を変更しようと考えています。  
水平方向のアライメントの指定によって、列単位に以下のように設定する
- 未指定 or 左寄せ　|:--|  
- 中央寄せ　|:--:|  
- 右寄せ　|--:|  

この問題の対処方法、または関連する内容で提案がある方はご協力ください。

**Comment by nuitsjp** [comment]
2016年10月25日24:00を持っていったん閉めて実装に入りたいと思います。

**Comment by amay077** [comment]
> Redmineでは|:--|のように間に挟まる文字列は３文字以上必要

GitHub の Markdown も同じく３文字以上必要なようなので、現在の提案でいいのかな、と思います。

**Comment by nuitsjp** [comment]
対応完了。クローズします。
