### ISSUE TITLE
表内の改行への対応

### ISSUE THREAD

**Issue by chie8842** [nuitsjp/CopyToMarkdownAddIn#3]
こんにちは。便利に使用させていただいているのですが、表内での改行の際、markdownでは、\r\nを<br>に置換しておかないと、表が壊れてしまいます。
できればご対応いただきたいです。
いったんforkしてソースコード変更してみたのですが、恥ずかしながらビルドの手順がわからず、動作確認できていません。
もしビルド方法をお教えいただければ、プルリク投げさせていただきたいです。

**Comment by nuitsjp** [comment]
お～なるほど。
ビルドは証明書が必要で、ちょっとこれはお渡しできませんのでプロジェクトのプロパティから仮証明書を作成してテストしていただけますでしょうか？
下図のあたりです。  

![0137](https://cloud.githubusercontent.com/assets/16175660/19672607/09393dae-9ab3-11e6-80da-8f2385a746da.png)

プルリクお待ちしています！

**Comment by chie8842** [comment]
すみません、Win10にvisualstudio2015をインストールしてみましたが、
The following projects are not supported by eigher this edition of Visual Studio or the version of Windowsとでてしまいます。。。
お手数ですが、ビルド環境をお教えいただけないでしょうか。

**Comment by nuitsjp** [comment]
OSはWindows 10 64bit のアニバーサリーエディション。（OSは問題ない気がします）
VSは2015のUpdate 3です。  
拡張機能としてOffice Developer Tools for Visual Studio 2015が入っている必要があります。
これはVSインストーラのカスタム
他は特にないと思いますが。。。

![0138](https://cloud.githubusercontent.com/assets/16175660/19674916/3a32697c-9ac6-11e6-9fbf-811c40aa5121.png)

Web Platform Installerから入れられると思います。
![0139](https://cloud.githubusercontent.com/assets/16175660/19675016/e5441504-9ac6-11e6-9549-5930a1594809.png)

**Comment by chie8842** [comment]
すみません、できました。プルリク送りました。
スクリーンショットなど丁寧にありがとうございました。

**Comment by nuitsjp** [comment]
RPありがとうございます！
RP側にも書きましたが、ヘッダー側にも同様のロジックを適用して、且つ処理をメソッドに切り出したいです。
こちらで対応しても構いませんが、よかったらRP送ってもらえると嬉しいのですが、どういたしましょう？

**Comment by chie8842** [comment]
あ！たしかに。すみません、headerの方は修正しました。
わたしC#はあまり書きなれていないこともあり、切り出し単位の好みなどもあるかと思いますので、
一旦マージいただいた後に変更していただいたほうがよいかな、と考えています。

**Comment by nuitsjp** [comment]
OKです。いったんマージしました。
後はこちらで対応します。
リリースまで少々お待ちください。
ご協力ありがとうございました！
