### ISSUE TITLE
MarkdownからExcelへの貼り付けを行うメニュー名が紛らわしい

### ISSUE THREAD

**Issue by NOGPON** [nuitsjp/CopyToMarkdownAddIn#7]
Excel ⇒ Markdown も Markdown ⇒ Excel もどちらもメニュー名が `Copy` で始まり、`to` と `from` で機能の識別をする必要があって紛らわしい。  
MarkdownのテーブルをExcelに貼り付ける時のメニュー名は、「Copy from Markdown」より「Paste from Markdown」などとした方が動きが分かりやすいと思う。

**Comment by nuitsjp** [comment]
なるほど、ちょっと考えてみます。
恐らくそのように修正して近いうちにリリースさせていただきます。
ご提言ありがとうございました！

**Comment by nuitsjp** [comment]
修正しました。
ご協力ありがとうございました。
https://github.com/nuitsjp/CopyToMarkdownAddIn/commit/12a70bf7c39edb5546544149737caeb066c008ba
